### ISSUE TITLE
Use a logger

### ISSUE THREAD

**Issue by jelmstrom** [debe82/SpringBoot-Loan-Calculator#1]
https://github.com/debe82/SpringBoot-Loan-Calculator/blob/67b0731568431d15fba4189213e302789829fce3/backend/src/main/java/se/kontek/backend/model/house/HouseLoanController.java#L27

Its better practice to use a `Logger` in java. That way you can add logs of different importance. Look at https://slf4j.org/

**Comment by debe82** [comment]
deleted all sout and replaced with a logger (not loggining anything in the final version)
