### ISSUE TITLE
Not found?

### ISSUE THREAD

**Issue by jelmstrom** [debe82/SpringBoot-Loan-Calculator#2]
I'd say if you cant find a plan the correct statuscode is 404.  400 is ok, but more detailed is better

https://github.com/debe82/SpringBoot-Loan-Calculator/blob/67b0731568431d15fba4189213e302789829fce3/backend/src/main/java/se/kontek/backend/model/house/HouseLoanController.java#LL26C1-L26C1

**Comment by debe82** [comment]
reoplaced badRequest with notFound
