### ISSUE TITLE
remove or add tests

### ISSUE THREAD

**Issue by jelmstrom** [debe82/SpringBoot-Loan-Calculator#4]
In Spring there are ways to test an API.  Look at these docs https://spring.io/guides/gs/testing-web/

https://github.com/debe82/SpringBoot-Loan-Calculator/blob/67b0731568431d15fba4189213e302789829fce3/backend/src/test/java/se/kontek/backend/model/house/HouseLoanControllerTest.java#L8

**Comment by debe82** [comment]
deleted HouseLoanControllerTest , tests performed via postman
