### ISSUE TITLE
unclear naming

### ISSUE THREAD

**Issue by jelmstrom** [debe82/SpringBoot-Loan-Calculator#6]
It says return "plan" but it returns a value, that by the looks of the tests and comments is a  numeric value of payments by month?
naming is important.

https://github.com/debe82/SpringBoot-Loan-Calculator/blob/67b0731568431d15fba4189213e302789829fce3/backend/src/main/java/se/kontek/backend/model/house/HouseLoan.java#L17

**Comment by debe82** [comment]
renamed getPlan with getMonthlyPayment
