### ISSUE TITLE
Cleanup

### ISSUE THREAD

**Issue by jelmstrom** [debe82/SpringBoot-Loan-Calculator#8]
There are comments that describe what the code does, that means the code is not explanatory enough,
Some better naming and simplifications are in place. Different variable names, extract into methods, etc...

https://github.com/debe82/SpringBoot-Loan-Calculator/blob/67b0731568431d15fba4189213e302789829fce3/backend/src/main/java/se/kontek/backend/model/house/HouseLoan.java#LL19C2-L31C1

**Comment by debe82** [comment]
removed comment, renamed methods and variables
